server:
  port: 8080
spring:
  # 配置发送方信息
  mail:
    host: smtp.qq.com
    username: 3106627097@qq.com  # 邮箱地址
    password: vvvbzfidfslzddba # 授权码
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  # thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    date-format: yyyy-MM-dd
  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test1
    password: 123456
    url: jdbc:mysql://47.96.126.180:3306/test1?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml